mkdir mytheme
cd mytheme

sudo apt update
sudo apt upgrade
sudo apt install gnome-tweaks -y
sudo apt install gnome-shell-extensions -y

mkdir mytheme
cd mytheme
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTQ3NjM4MzAiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6ImYwZjliN2QyNWMwYzE5ODM4NGI1MGZjYzg5YTM3MGUyMzgyZTk3MTUwM2QxNWY2ZjQ3NjUxNDgyYjEwMTdlNmRlYWQ3MWVkYTA0Mzk3Mzc1YzMyNTQ4YmQ2YmIxODg3ZGIxNmViZTQzYTg0MTgxNzU0MTMxMGEyZDI4Nzg2ZDNhIiwidCI6MTYxNTA1MTM1OSwic3RmcCI6ImNmZmU0YzFmOTRhN2I5ODYzYWVhNjQ2ZDMyNmZhMTA4Iiwic3RpcCI6IjE1MS42Mi4xMjcuMjQ3In0.kZv0bbkKmrUxNLrLMHePoD_EPEpVfq7kOrltvDNYgws/Mojave-dark.tar.xz
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTQ3NjM5ODUiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6ImU2YzllMTViMjYyOTc0NzdkOWQxOTRjZjUyN2ZjZDUxYmU0ZWJkNzE1ZDA0YzdiYzQ2NzFjZjdlMDI0MWIwNmZlNDBjNmU0YTlkZGM2ODY0MmM0NWQ3YjM4ZDA4NmQ0NDkxNWU1ZWIyMjNiNzQ0ZDA3YWI5ZGMwNjVmZDliZWUyIiwidCI6MTYxNTA1MTQyMiwic3RmcCI6ImNmZmU0YzFmOTRhN2I5ODYzYWVhNjQ2ZDMyNmZhMTA4Iiwic3RpcCI6IjE1MS42Mi4xMjcuMjQ3In0.iW1ZJi1EOGzPaVrFC-LK8U_bn1viZzMFwMRqOSeu2lc/Mojave-light.tar.xz
mkdir .theme
tar -xf Mojave-dark.tar.xz -C .theme
tar -xf Mojave-light.tar.xz -C .theme

mkdir .icons
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTQ1MTYyMDgiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjkyMmViNTU4MDJhNzUyN2FiOGFhNmUyNjc2NGZjZTU1ZmRmZTc0ZDE3ZGJkZjU3MWM5ZTliMDc4MmJmMTIzYjU0M2VlNzUzYWU3ZjE0ZTRmMTMxOGI1OWU0YmIxMTBjMTI5MjNhODkzNWI3MjdjY2VhZTk2ZjI0ODkwOTZmMzhmIiwidCI6MTYxNTA1MjE3OSwic3RmcCI6ImNmZmU0YzFmOTRhN2I5ODYzYWVhNjQ2ZDMyNmZhMTA4Iiwic3RpcCI6IjE1MS42Mi4xMjcuMjQ3In0.4l2s-gK7_pft5Us-XPmor28CTcKQS0SZ7zl9c6SqsaU/01-McMojave-circle.tar.xz
tar -xf 01-McMojave-circle.tar.xz -C .icons

gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false

gnome-tweaks
